Repository mybatis/spring-boot-starter, pull requests merged in 2022-05, with the labels that each got.

#652 Update to 2.3.0-SNAPSHOT on master branch
  mybatis-spring-boot-autoconfigure/pom.xml
  mybatis-spring-boot-samples/mybatis-spring-boot-sample-annotation/pom.xml
  mybatis-spring-boot-samples/mybatis-spring-boot-sample-freemarker-legacy/pom.xml
  mybatis-spring-boot-samples/mybatis-spring-boot-sample-freemarker/pom.xml
  mybatis-spring-boot-samples/mybatis-spring-boot-sample-groovy/pom.xml
  mybatis-spring-boot-samples/mybatis-spring-boot-sample-kotlin/pom.xml
  mybatis-spring-boot-samples/mybatis-spring-boot-sample-thymeleaf/pom.xml
  mybatis-spring-boot-samples/mybatis-spring-boot-sample-velocity-legacy/pom.xml
  mybatis-spring-boot-samples/mybatis-spring-boot-sample-velocity/pom.xml
  mybatis-spring-boot-samples/mybatis-spring-boot-sample-war/pom.xml
  mybatis-spring-boot-samples/mybatis-spring-boot-sample-web/pom.xml
  mybatis-spring-boot-samples/mybatis-spring-boot-sample-xml/pom.xml
  mybatis-spring-boot-samples/pom.xml
  mybatis-spring-boot-starter-test/pom.xml
  mybatis-spring-boot-starter/pom.xml
  mybatis-spring-boot-test-autoconfigure/pom.xml
  pom.xml
Labels: enhancement

#638 avoid resolving MapperLocations twice
  mybatis-spring-boot-autoconfigure/src/main/java/org/mybatis/spring/boot/autoconfigure/MybatisAutoConfiguration.java
Labels: polishing

#651 Support Chinese translations on autoconfigure reference doc
  mybatis-spring-boot-autoconfigure/src/site/markdown/zh/index.md
Labels: documentation

#659 Support multi language on reference document
  README.md
  mybatis-spring-boot-autoconfigure/src/site/markdown/index.md
  mybatis-spring-boot-autoconfigure/src/site/resources/css/site.css
  mybatis-spring-boot-autoconfigure/src/site/resources/es/css/site.css
  mybatis-spring-boot-autoconfigure/src/site/resources/images/en.png
  mybatis-spring-boot-autoconfigure/src/site/resources/images/es.png
  mybatis-spring-boot-autoconfigure/src/site/resources/images/ja.png
  mybatis-spring-boot-autoconfigure/src/site/resources/images/ko.png
  mybatis-spring-boot-autoconfigure/src/site/resources/images/zh.png
  mybatis-spring-boot-autoconfigure/src/site/resources/ja/css/site.css
  mybatis-spring-boot-autoconfigure/src/site/resources/ko/css/site.css
  mybatis-spring-boot-autoconfigure/src/site/resources/zh/css/site.css
  mybatis-spring-boot-autoconfigure/src/site/site_zh.xml
  mybatis-spring-boot-autoconfigure/src/site/zh/markdown/index.md
  pom.xml
Labels: documentation

#661 Support JDK 18-GA on CI
  .github/workflows/ci.yaml
  .github/workflows/support.yaml
Labels: enhancement
